In [3]:
import pandas as pd

In [25]:
df=pd.read_csv(r"C:\Users\brije\Downloads\pizza_sales.csv\pizza_sales.csv")
df

,pizza_id,order_id,pizza_name_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_ingredients,pizza_name
0,1.0,1.0,hawaiian_m,1.0,1/1/2015,11:38:36,13.25,13.25,M,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",The Hawaiian Pizza
1,2.0,2.0,classic_dlx_m,1.0,1/1/2015,11:57:40,16.00,16.00,M,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",The Classic Deluxe Pizza
2,3.0,2.0,five_cheese_l,1.0,1/1/2015,11:57:40,18.50,18.50,L,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",The Five Cheese Pizza
3,4.0,2.0,ital_supr_l,1.0,1/1/2015,11:57:40,20.75,20.75,L,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",The Italian Supreme Pizza
4,5.0,2.0,mexicana_m,1.0,1/1/2015,11:57:40,16.00,16.00,M,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza
...,...,...,...,...,...,...,...,...,...,...,...,...
48615,48616.0,21348.0,ckn_alfredo_m,1.0,31-12-2015,21:23:10,16.75,16.75,M,Chicken,"Chicken, Red Onions, Red Peppers, Mushrooms, A...",The Chicken Alfredo Pizza
48616,48617.0,21348.0,four_cheese_l,1.0,31-12-2015,21:23:10,17.95,17.95,L,Veggie,"Ricotta Cheese, Gorgonzola Piccante Cheese, Mo...",The Four Cheese Pizza
48617,48618.0,21348.0,napolitana_s,1.0,31-12-2015,21:23:10,12.00,12.00,S,Classic,"Tomatoes, Anchovies, Green Olives, Red Onions,...",The Napolitana Pizza
48618,48619.0,21349.0,mexicana_l,1.0,31-12-2015,22:09:54,20.25,20.25,L,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza
48619,48620.0,21350.0,bbq_ckn_s,1.0,31-12-2015,23:02:05,12.75,12.75,S,Chicken,"Barbecued Chicken, Red Peppers, Green Peppers,...",The Barbecue Chicken Pizza

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48620 entries, 0 to 48619
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   pizza_id           48620 non-null  float64
 1   order_id           48620 non-null  float64
 2   pizza_name_id      48620 non-null  object
 3   quantity           48620 non-null  float64
 4   order_date         48620 non-null  object
 5   order_time         48620 non-null  object
 6   unit_price         48620 non-null  float64
 7   total_price        48620 non-null  float64
 8   pizza_size         48620 non-null  object
 9   pizza_category     48620 non-null  object
 10  pizza_ingredients  48620 non-null  object
 11  pizza_name         48620 non-null  object
dtypes: float64(5), object(7)
memory usage: 4.5+ MB

In [27]:
df.isnull().sum()

pizza_id             0
order_id             0
pizza_name_id        0
quantity             0
order_date           0
order_time           0
unit_price           0
total_price          0
pizza_size           0
pizza_category       0
pizza_ingredients    0
pizza_name           0
dtype: int64

In [28]:
df["pizza_size"].unique()

array(['M', 'L', 'S', 'XL', 'XXL'], dtype=object)

In [29]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
df["pizza_size"]=encoder.fit_transform(df["pizza_size"])

In [30]:
df

,pizza_id,order_id,pizza_name_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_ingredients,pizza_name
0,1.0,1.0,hawaiian_m,1.0,1/1/2015,11:38:36,13.25,13.25,1,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",The Hawaiian Pizza
1,2.0,2.0,classic_dlx_m,1.0,1/1/2015,11:57:40,16.00,16.00,1,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",The Classic Deluxe Pizza
2,3.0,2.0,five_cheese_l,1.0,1/1/2015,11:57:40,18.50,18.50,0,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",The Five Cheese Pizza
3,4.0,2.0,ital_supr_l,1.0,1/1/2015,11:57:40,20.75,20.75,0,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",The Italian Supreme Pizza
4,5.0,2.0,mexicana_m,1.0,1/1/2015,11:57:40,16.00,16.00,1,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza
...,...,...,...,...,...,...,...,...,...,...,...,...
48615,48616.0,21348.0,ckn_alfredo_m,1.0,31-12-2015,21:23:10,16.75,16.75,1,Chicken,"Chicken, Red Onions, Red Peppers, Mushrooms, A...",The Chicken Alfredo Pizza
48616,48617.0,21348.0,four_cheese_l,1.0,31-12-2015,21:23:10,17.95,17.95,0,Veggie,"Ricotta Cheese, Gorgonzola Piccante Cheese, Mo...",The Four Cheese Pizza
48617,48618.0,21348.0,napolitana_s,1.0,31-12-2015,21:23:10,12.00,12.00,2,Classic,"Tomatoes, Anchovies, Green Olives, Red Onions,...",The Napolitana Pizza
48618,48619.0,21349.0,mexicana_l,1.0,31-12-2015,22:09:54,20.25,20.25,0,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza
48619,48620.0,21350.0,bbq_ckn_s,1.0,31-12-2015,23:02:05,12.75,12.75,2,Chicken,"Barbecued Chicken, Red Peppers, Green Peppers,...",The Barbecue Chicken Pizza

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48620 entries, 0 to 48619
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   pizza_id           48620 non-null  float64
 1   order_id           48620 non-null  float64
 2   pizza_name_id      48620 non-null  object
 3   quantity           48620 non-null  float64
 4   order_date         48620 non-null  object
 5   order_time         48620 non-null  object
 6   unit_price         48620 non-null  float64
 7   total_price        48620 non-null  float64
 8   pizza_size         48620 non-null  int64
 9   pizza_category     48620 non-null  object
 10  pizza_ingredients  48620 non-null  object
 11  pizza_name         48620 non-null  object
dtypes: float64(5), int64(1), object(6)
memory usage: 4.5+ MB

In [32]:
df.duplicated().sum()

np.int64(0)

In [33]:
df["pizza_category"].unique()

array(['Classic', 'Veggie', 'Supreme', 'Chicken'], dtype=object)

In [34]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
df["pizza_category"]=encoder.fit_transform(df["pizza_category"])

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48620 entries, 0 to 48619
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   pizza_id           48620 non-null  float64
 1   order_id           48620 non-null  float64
 2   pizza_name_id      48620 non-null  object
 3   quantity           48620 non-null  float64
 4   order_date         48620 non-null  object
 5   order_time         48620 non-null  object
 6   unit_price         48620 non-null  float64
 7   total_price        48620 non-null  float64
 8   pizza_size         48620 non-null  int64
 9   pizza_category     48620 non-null  int64
 10  pizza_ingredients  48620 non-null  object
 11  pizza_name         48620 non-null  object
dtypes: float64(5), int64(2), object(5)
memory usage: 4.5+ MB

In [36]:
df

,pizza_id,order_id,pizza_name_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_ingredients,pizza_name
0,1.0,1.0,hawaiian_m,1.0,1/1/2015,11:38:36,13.25,13.25,1,1,"Sliced Ham, Pineapple, Mozzarella Cheese",The Hawaiian Pizza
1,2.0,2.0,classic_dlx_m,1.0,1/1/2015,11:57:40,16.00,16.00,1,1,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",The Classic Deluxe Pizza
2,3.0,2.0,five_cheese_l,1.0,1/1/2015,11:57:40,18.50,18.50,0,3,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",The Five Cheese Pizza
3,4.0,2.0,ital_supr_l,1.0,1/1/2015,11:57:40,20.75,20.75,0,2,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",The Italian Supreme Pizza
4,5.0,2.0,mexicana_m,1.0,1/1/2015,11:57:40,16.00,16.00,1,3,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza
...,...,...,...,...,...,...,...,...,...,...,...,...
48615,48616.0,21348.0,ckn_alfredo_m,1.0,31-12-2015,21:23:10,16.75,16.75,1,0,"Chicken, Red Onions, Red Peppers, Mushrooms, A...",The Chicken Alfredo Pizza
48616,48617.0,21348.0,four_cheese_l,1.0,31-12-2015,21:23:10,17.95,17.95,0,3,"Ricotta Cheese, Gorgonzola Piccante Cheese, Mo...",The Four Cheese Pizza
48617,48618.0,21348.0,napolitana_s,1.0,31-12-2015,21:23:10,12.00,12.00,2,1,"Tomatoes, Anchovies, Green Olives, Red Onions,...",The Napolitana Pizza
48618,48619.0,21349.0,mexicana_l,1.0,31-12-2015,22:09:54,20.25,20.25,0,3,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza
48619,48620.0,21350.0,bbq_ckn_s,1.0,31-12-2015,23:02:05,12.75,12.75,2,0,"Barbecued Chicken, Red Peppers, Green Peppers,...",The Barbecue Chicken Pizza

In [37]:
df["order_time"]=pd.to_datetime(df["order_time"])
df["hour"]=df["order_time"].dt.hour

C:\Users\brije\AppData\Local\Temp\ipykernel_16436\1877311995.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["order_time"]=pd.to_datetime(df["order_time"])

In [38]:
df

,pizza_id,order_id,pizza_name_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_ingredients,pizza_name,hour
0,1.0,1.0,hawaiian_m,1.0,1/1/2015,2026-04-14 11:38:36,13.25,13.25,1,1,"Sliced Ham, Pineapple, Mozzarella Cheese",The Hawaiian Pizza,11
1,2.0,2.0,classic_dlx_m,1.0,1/1/2015,2026-04-14 11:57:40,16.00,16.00,1,1,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",The Classic Deluxe Pizza,11
2,3.0,2.0,five_cheese_l,1.0,1/1/2015,2026-04-14 11:57:40,18.50,18.50,0,3,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",The Five Cheese Pizza,11
3,4.0,2.0,ital_supr_l,1.0,1/1/2015,2026-04-14 11:57:40,20.75,20.75,0,2,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",The Italian Supreme Pizza,11
4,5.0,2.0,mexicana_m,1.0,1/1/2015,2026-04-14 11:57:40,16.00,16.00,1,3,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...
48615,48616.0,21348.0,ckn_alfredo_m,1.0,31-12-2015,2026-04-14 21:23:10,16.75,16.75,1,0,"Chicken, Red Onions, Red Peppers, Mushrooms, A...",The Chicken Alfredo Pizza,21
48616,48617.0,21348.0,four_cheese_l,1.0,31-12-2015,2026-04-14 21:23:10,17.95,17.95,0,3,"Ricotta Cheese, Gorgonzola Piccante Cheese, Mo...",The Four Cheese Pizza,21
48617,48618.0,21348.0,napolitana_s,1.0,31-12-2015,2026-04-14 21:23:10,12.00,12.00,2,1,"Tomatoes, Anchovies, Green Olives, Red Onions,...",The Napolitana Pizza,21
48618,48619.0,21349.0,mexicana_l,1.0,31-12-2015,2026-04-14 22:09:54,20.25,20.25,0,3,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza,22
48619,48620.0,21350.0,bbq_ckn_s,1.0,31-12-2015,2026-04-14 23:02:05,12.75,12.75,2,0,"Barbecued Chicken, Red Peppers, Green Peppers,...",The Barbecue Chicken Pizza,23

In [39]:
df2=df.select_dtypes(["int","float"])
df2

,pizza_id,order_id,quantity,unit_price,total_price,pizza_size,pizza_category,hour
0,1.0,1.0,1.0,13.25,13.25,1,1,11
1,2.0,2.0,1.0,16.00,16.00,1,1,11
2,3.0,2.0,1.0,18.50,18.50,0,3,11
3,4.0,2.0,1.0,20.75,20.75,0,2,11
4,5.0,2.0,1.0,16.00,16.00,1,3,11
...,...,...,...,...,...,...,...,...
48615,48616.0,21348.0,1.0,16.75,16.75,1,0,21
48616,48617.0,21348.0,1.0,17.95,17.95,0,3,21
48617,48618.0,21348.0,1.0,12.00,12.00,2,1,21
48618,48619.0,21349.0,1.0,20.25,20.25,0,3,22
48619,48620.0,21350.0,1.0,12.75,12.75,2,0,23

In [40]:
df2.corr()

,pizza_id,order_id,quantity,unit_price,total_price,pizza_size,pizza_category,hour
pizza_id,1.000000,0.999990,0.003639,-0.003286,-0.000847,0.001404,-0.006258,0.006392
order_id,0.999990,1.000000,0.003621,-0.003323,-0.000889,0.001425,-0.006296,0.006419
quantity,0.003639,0.003621,1.000000,0.007142,0.541926,-0.014406,-0.012405,-0.058092
unit_price,-0.003286,-0.003323,0.007142,1.000000,0.836087,-0.725761,-0.001022,-0.000677
total_price,-0.000847,-0.000889,0.541926,0.836087,1.000000,-0.612686,-0.007306,-0.031766
pizza_size,0.001404,0.001425,-0.014406,-0.725761,-0.612686,1.000000,-0.050364,0.004065
pizza_category,-0.006258,-0.006296,-0.012405,-0.001022,-0.007306,-0.050364,1.000000,0.000413
hour,0.006392,0.006419,-0.058092,-0.000677,-0.031766,0.004065,0.000413,1.000000

In [41]:
df2.isnull().sum()

pizza_id          0
order_id          0
quantity          0
unit_price        0
total_price       0
pizza_size        0
pizza_category    0
hour              0
dtype: int64

In [42]:
df.isnull().sum()

pizza_id             0
order_id             0
pizza_name_id        0
quantity             0
order_date           0
order_time           0
unit_price           0
total_price          0
pizza_size           0
pizza_category       0
pizza_ingredients    0
pizza_name           0
hour                 0
dtype: int64

In [43]:
x=df[["quantity","pizza_size","pizza_category","hour"]]
y=df["total_price"]

In [44]:
from sklearn import linear_model

In [45]:
regr=linear_model.LinearRegression()
regr.fit(x,y)

LinearRegression()

In [46]:
df["pizza_size"].unique()

array([1, 0, 2, 3, 4])

In [47]:
df["pizza_category"].unique()

array([1, 3, 2, 0])

In [56]:
predicted=regr.predict([[2,4,4,11]])
predicted

C:\Users\brije\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([22.9465004])

In [57]:
print(predicted)

[22.9465004]

In [58]:
predicted2=regr.predict(x)
predicted2

array([16.33837152, 16.33837152, 19.25950525, ..., 13.18393031,
       19.28538807, 13.31705493], shape=(48620,))

In [59]:
from sklearn.metrics import r2_score
print(r2_score(y,predicted2))

0.6606156353046053